### ISSUE TITLE
suzu: Settings not working

### ISSUE THREAD

**Issue by ruedigerkupper** [fredldotme/ISODriveUT#10]
Tapping the gear sign in the upper right corner does nothing at all on the Xperia.

**Comment by fredldotme** [comment]
The settings don't have an effect on ConfigFS devices like the Xperia X as everything is done automatically there.

**Comment by ruedigerkupper** [comment]
Oh, hey, that's great. Does this also refer to #6 (accessing phone's data while booted into the image)?

**Comment by fredldotme** [comment]
Yes
