### ISSUE TITLE
Feature suggestion: access phone's data while being booted

### ISSUE THREAD

**Issue by ruedigerkupper** [fredldotme/ISODriveUT#6]
This tool is dead useful! It boots a lot faster than any of the (usually crappy) USB thumb drives I ever got my fingers on. Great work!

Here's a feature suggestion:
It would be absolutely smashing if we could access the files in the phone's home folder while booted into the iso. This would instantly turn my phone into a mobile workstation. I could boot any PC around into an Ubuntu live session, fire up Libreoffice and work on my files.
THIS would be a killer app! Something convergence always promised to us but never delivered …

**Comment by fredldotme** [comment]
A quick test resulted in this working fine. It has been implemented as a setting you'll have to enable yourself (commit 37161d41201f47a3505e29d8878043c050192b82) and will be released as part of ISODriveUT v0.6.3

**Comment by ruedigerkupper** [comment]
That is phenomenal news. Thank you for implementing so quickly!
