### ISSUE TITLE
Can NOT connect to booted ISO

### ISSUE THREAD

**Issue by andorgergo** [fredldotme/ISODriveUT#8]
Dear Alfred!

I can't get this tool working yet. 
ISODrive boots my downloaded ISO files, so I see the message in the header, e.g. "Active: debian-10.1.0-armhf-xfce-CD-1.iso". **But I can't connect to the UI of the booted image.** Tapping on the ISO won't work. **How can I connect to the ISO? Should it pop up in a new window?**

Parameters:
device: BQ aquaris m10 FHD
OS: Ubuntu 16.04 OTA-9 (2019.06.06.)
developer mode: On (I tried it with Off setting too.)
ISO files: ubuntu, debian ISO-s

**What kind of ISO files are supported?** Only armhf? Ore everything?

Many thank's for your work!
Greg

**Comment by fredldotme** [comment]
It's hard for me to understand what you are trying to achieve.
For reference, have you tried with an Ubuntu ISO if that's booting?

**Comment by andorgergo** [comment]
I started the ubuntu 18.04.3 amd64 image and got the following UI:
![screenshot20191104_214207270](https://user-images.githubusercontent.com/48478732/68160057-3ea6d480-ff53-11e9-9989-e710ca16db5a.png)

So the image is active, I guess it's booting, **but I do not see the user interface of Ubuntu**. 
It did not pop up in another window, so something is wrong. How can I access the UI?

**Comment by fredldotme** [comment]
This seems to be an issue with your graphics drivers because ISODrive doesn't do anything in that regard, it just provides the drive for the PC to boot up.

**Comment by arubislander** [comment]
This is an old issue. But it is still open, so here's my € 0,02: The OP was expecting the ISO image to boot up on their mobile device. The OP did not understand they had to connect their device to a laptop or desktop and use that to boot into the ISO image.

**Comment by fredldotme** [comment]
Yeah, I guess so. I'll close this issue then. Thanks!
