### ISSUE TITLE
ARM/AMD 64 support

### ISSUE THREAD

**Issue by ghost** [fredldotme/ISODriveUT#9]
I would like to use this app on my OnePlus 3T.
Any plans?

**Comment by fredldotme** [comment]
arm64 and amd64 builds are already available on the OpenStore.

**Comment by ghost** [comment]
Really?
![screenshot20200325_142837514](https://user-images.githubusercontent.com/46136222/77541570-1f2e2b00-6ea5-11ea-8bec-9b2bfe009e6d.png)

**Comment by fredldotme** [comment]
Could you please check again now?

**Comment by ghost** [comment]
Works, thanks!
